<?php

namespace SancAbsBundle\Repository;

/**
 * SanctionemployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionemployeRepository extends \Doctrine\ORM\EntityRepository
{
}
