almni_homepage:
    path:     /
    defaults: { _controller: AlmniBundle:Default:index }

almni_about:
    path:     /about
    defaults: { _controller: AlmniBundle:Default:about }

almni_admin:
    path:     /adminpanel
    defaults: { _controller: AlmniBundle:Admin:index }


almni_admin_test:
    path:     /adminpanel/test
    defaults: { _controller: AlmniBundle:Admin:test }
