<?php

namespace ProfilBundle\Repository;

/**
 * ProfilprofRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilprofRepository extends \Doctrine\ORM\EntityRepository
{
}
