<?php

namespace ProfilBundle\Repository;

/**
 * ProfileleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileleveRepository extends \Doctrine\ORM\EntityRepository
{
}
