<?php

namespace ProfilBundle\Repository;

/**
 * ProfilparentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilparentRepository extends \Doctrine\ORM\EntityRepository
{
}
