<?php

namespace ProfilBundle\Repository;

/**
 * ProfiladminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfiladminRepository extends \Doctrine\ORM\EntityRepository
{
}
